name: CALAYO
description: Flutter port of the Android E-commerce main customer flows
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.0
  firebase_messaging: ^14.9.0

  # State Management
  provider: ^6.0.5

  # Local Storage
  shared_preferences: ^2.1.1

  # UI & Utility
  cupertino_icons: ^1.0.2
  flutter_map: ^6.1.0 # Updated from 7.0.0 to a more stable version
  latlong2: ^0.9.0
  image_picker: ^1.0.4 # Updated from 1.1.2

dev_dependencies:
  flutter_lints: ^2.0.0 # Moved to dev_dependencies

flutter:
  uses-material-design: true
  assets:
    - assets/images/
